### ISSUE TITLE
twine is asking for my username even though i configured my pypi credentials

### ISSUE THREAD

**Issue by iomintz** [duckinator/bork#153]
I have my ~/.pypirc set up like this
```ini
[distutils]
index-servers =
    pypi
    testpypi

[pypi]
repository=https://upload.pypi.org/legacy/
username=...
password=...

[testpypi]
repository=https://test.pypi.org/legacy/
username=...
password=...
```
I can run `twine upload dist/<file>.tar.gz` just fine, but when I try to run `twine upload --repository-url https://upload.pypi.org/legacy/ dist/<file>.tar.gz`, as bork does, twine asks me for my username.

**Comment by duckinator** [comment]
I poked around and found a few things:

1. According to `twine upload --help`, you can use `--repository <REPOSITORY>` if you define one in `.pypirc`.
2. According to [the specification for for `.pypirc`](https://packaging.python.org/specifications/pypirc/#common-configurations), Twine defaults to having definitions for pypi and testpypi.

As I understand it, this means if Bork uses `--repository pypi`/`--repository testpypi` instead of `--repository-url`, it'll use either those defaults or any overrides you specify.

@iomintz that should solve your problem, right?

**Comment by duckinator** [comment]
In terms of implementation, I'd probably:

1. Add a `--pypi-repository <REPOSITORY>` flag which gets passed to Twine as `--repository <REPOSITORY>`.
2. Make `--test-pypi` an alias for `--pypi-repository testpypi`.

**Comment by iomintz** [comment]
Yeah I think that should do it.

**Comment by iomintz** [comment]
Confirmed, that flag doesn't ask me for credentials on the command line.

**Comment by duckinator** [comment]
Awesome, thanks for confirming that. I made this part of the [v4.0.0 milestone](https://github.com/duckinator/bork/milestone/1), which is planned to be released early next week.

**Comment by duckinator** [comment]
@iomintz PR #156 should resolve the issue. I'll post another update here when there's a release including it.

**Comment by iomintz** [comment]
Thanks for the followups.

**Comment by duckinator** [comment]
@iomintz v4.0.1 was released just now, which includes a fix for this. If you still have this problem leave a comment here and I'll re-open the issue!

https://github.com/duckinator/bork/releases/tag/v4.0.1
