### ISSUE TITLE
Investigate better bors/GitHub integration?

### ISSUE THREAD

**Issue by duckinator** [duckinator/bork#236]
Follow-up to #234.

My idea is, basically:

1. Have a Cirrus CI task named something like "CI_Success_task", which does nothing but relies on all other CI tasks.
2. Have bors rely on _just_ that task.

This lets us have all the CI-related configuration that's prone to changing over time in one place.

@nbraud: what are your thoughts on this approach?

**Comment by nbraud** [comment]
3 main thoughts:
1. I already find `.cirrus.yml` just large enough to be annoying to navigate, so it's actually slightly more convenient *when editing the set of tasks Bors waits on* to have it in `bors.toml`.
2. If we use an [alias] in each task definition (to captures all instances for all versions of Python we test against), then editing that set would be much, much less frequent and error-prone.
3. Reversing the relationship (i.e. having a `depended_on_by` on each relevant task, rather than a `depends_on` list in the `CI_Success_task`) would be even better, but I don't think the Cirrus config language supports that.

:+1: from me overall

[alias]: https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies
